import OptimalQLS.LowerBounds.FiniteProgramOneSided
import OptimalQLS.LowerBounds.FiniteProgramDensity

/-!
# Unbounded finitely branching quantum programs with typed finite registers

A program is an instruction coalgebra, so loops and unbounded classical
control are allowed. Register dimensions change through actual rectangular
Kraus instruments. Finite prefixes are generated by recursion on fuel; fuel
exhaustion executes the concrete normalized abort instrument.
-/
noncomputable section
open scoped BigOperators Matrix.Norms.L2Operator
namespace OptimalQLS.LowerBounds
open Matrix
universe u v r

inductive QuantumInstruction (A : Type u) (B : Type v) (d : ℕ) (Node : ℕ → Type r) : ℕ → Type (max u v r) where
  | output (success : Bool) : QuantumInstruction A B d Node d
  | matrixQuery {w : ℕ} (port : OptimalQLS.QueryPort A (Fin w)) (adjoint : Bool) (next : Node w) : QuantumInstruction A B d Node w
  | vectorQuery {w : ℕ} (port : OptimalQLS.QueryPort B (Fin w)) (adjoint : Bool) (next : Node w) : QuantumInstruction A B d Node w
  | instrument {w : ℕ} (rank : ℕ) (nextDimension : Fin rank → ℕ)
      (K : ∀ i, Matrix (Fin (nextDimension i)) (Fin w) ℂ)
      (normalized : ∑ i, (K i).conjTranspose * K i = 1)
      (next : ∀ i, Node (nextDimension i)) : QuantumInstruction A B d Node w

structure QuantumProgram (A : Type u) (B : Type v) (d : ℕ) (Node : ℕ → Type r) where
  step : {w : ℕ} → Node w → QuantumInstruction A B d Node w

variable {A : Type u} {B : Type v} {d w : ℕ} {Node : ℕ → Type r}

def QuantumProgram.unroll (program : QuantumProgram A B d Node) (out : Fin d) :
    (fuel : ℕ) → {w : ℕ} → Node w → FiniteOracleProgram A B d w
  | 0, w, _ => FiniteOracleProgram.abortProgram out w
  | fuel + 1, _, node => match program.step node with
    | .output success => .output success false
    | .matrixQuery port adj next => .matrixQuery port adj (program.unroll out fuel next)
    | .vectorQuery port adj next => .vectorQuery port adj (program.unroll out fuel next)
    | .instrument rank dims K hn next => .instrument rank dims K hn (fun i => program.unroll out fuel (next i))

theorem QuantumProgram.unroll_vectorDepth_le (program : QuantumProgram A B d Node)
    (out : Fin d) (fuel : ℕ) (node : Node w) : (program.unroll out fuel node).vectorDepth ≤ fuel := by
  induction fuel generalizing w with
  | zero => simp [unroll]
  | succ fuel ih =>
    unfold unroll
    cases program.step node with
    | output success => simp [FiniteOracleProgram.vectorDepth]
    | matrixQuery port adj next => exact (ih next).trans (Nat.le_succ fuel)
    | vectorQuery port adj next => exact Nat.succ_le_succ (ih next)
    | instrument rank dims K hn next =>
      apply Finset.sup_le
      intro i _
      exact (ih (next i)).trans (Nat.le_succ fuel)

/-- For a finite approximation, fuel exhaustion can be counted as ordinary
failure before applying the separate vector-query stopping transformation. -/
def FiniteOracleProgram.eraseAbort : {w : ℕ} → FiniteOracleProgram A B d w → FiniteOracleProgram A B d w
  | _, .output success _ => .output success false
  | _, .matrixQuery port adj next => .matrixQuery port adj next.eraseAbort
  | _, .vectorQuery port adj next => .vectorQuery port adj next.eraseAbort
  | _, .instrument rank dims K hn next => .instrument rank dims K hn (fun i => (next i).eraseAbort)

theorem FiniteOracleProgram.eraseAbort_clean (tree : FiniteOracleProgram A B d w) : tree.eraseAbort.Clean := by
  induction tree with
  | output success aborted => intro k; rfl
  | matrixQuery port adj next ih => exact ih
  | vectorQuery port adj next ih => exact ih
  | instrument rank dims K hn next ih => exact fun k => ih k.1 k.2

@[simp] theorem FiniteOracleProgram.eraseAbort_vectorDepth (tree : FiniteOracleProgram A B d w) :
    tree.eraseAbort.vectorDepth = tree.vectorDepth := by
  induction tree with
  | output success aborted => rfl
  | matrixQuery port adj next ih => exact ih
  | vectorQuery port adj next ih => exact congrArg (· + 1) ih
  | instrument rank dims K hn next ih => simp [eraseAbort, vectorDepth, ih]

def FiniteOracleProgram.eraseAbort_terminalEquiv : {w : ℕ} → (tree : FiniteOracleProgram A B d w) → tree.eraseAbort.Terminal ≃ tree.Terminal
  | _, .output _ _ => Equiv.refl Unit
  | _, .matrixQuery _ _ next => next.eraseAbort_terminalEquiv
  | _, .vectorQuery _ _ next => next.eraseAbort_terminalEquiv
  | _, .instrument _ _ _ _ next => Equiv.sigmaCongrRight (fun i => (next i).eraseAbort_terminalEquiv)

variable [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]

theorem FiniteOracleProgram.eraseAbort_executeDensity (tree : FiniteOracleProgram A B d w)
    (UA : Matrix.unitaryGroup A ℂ) (Ub : Matrix.unitaryGroup B ℂ) (select : Bool → Bool) (psi : Fin w → ℂ) :
    tree.eraseAbort.executeDensity UA Ub select psi = tree.executeDensity UA Ub select psi := by
  induction tree with
  | output success aborted => rfl
  | matrixQuery port adj next ih => exact ih _
  | vectorQuery port adj next ih => exact ih _
  | instrument rank dims K hn next ih =>
    change (∑ i, _) = ∑ i, _
    exact Finset.sum_congr rfl (fun i _ => ih i _)

/-- Retagging fuel aborts preserves the full success/failure output channel on
the actual input, not only its scalar success probability. -/
theorem FiniteOracleProgram.eraseAbort_outputChannel (tree : FiniteOracleProgram A B d w)
    (UA : Matrix.unitaryGroup A ℂ) (Ub : Matrix.unitaryGroup B ℂ) (psi : Fin w → ℂ) :
    (tree.eraseAbort.outputChannel UA Ub).apply (pureDensity psi) = (tree.outputChannel UA Ub).apply (pureDensity psi) := by
  rw [tree.eraseAbort.outputChannel_pureDensity, tree.outputChannel_pureDensity,
    tree.eraseAbort_executeDensity, tree.eraseAbort_executeDensity]

theorem FiniteOracleProgram.eraseAbort_terminalKraus (tree : FiniteOracleProgram A B d w)
    (UA : Matrix.unitaryGroup A ℂ) (Ub : Matrix.unitaryGroup B ℂ) (k : tree.eraseAbort.Terminal) :
    tree.eraseAbort.terminalKraus UA Ub k = tree.terminalKraus UA Ub (tree.eraseAbort_terminalEquiv k) := by
  induction tree with
  | output success aborted => rfl
  | matrixQuery port adj next ih => exact congrArg (fun X => X * _) (ih k)
  | vectorQuery port adj next ih => exact congrArg (fun X => X * _) (ih k)
  | instrument rank dims K hn next ih => exact congrArg (fun X => X * K k.1) (ih k.1 k.2)

theorem FiniteOracleProgram.eraseAbort_terminalVectorQueries (tree : FiniteOracleProgram A B d w)
    (k : tree.eraseAbort.Terminal) :
    tree.eraseAbort.terminalVectorQueries k = tree.terminalVectorQueries (tree.eraseAbort_terminalEquiv k) := by
  induction tree with
  | output success aborted => rfl
  | matrixQuery port adj next ih => exact ih k
  | vectorQuery port adj next ih => exact congrArg (· + 1) (ih k)
  | instrument rank dims K hn next ih => exact ih k.1 k.2

theorem FiniteOracleProgram.eraseAbort_pointwiseVectorBound (tree : FiniteOracleProgram A B d w)
    (UA : Matrix.unitaryGroup A ℂ) (Ub : Matrix.unitaryGroup B ℂ) (psi : Fin w → ℂ) (q : ℕ)
    (hq : tree.PointwiseVectorBound UA Ub psi q) : tree.eraseAbort.PointwiseVectorBound UA Ub psi q := by
  intro k hk
  rw [terminalBorn, tree.eraseAbort_terminalKraus] at hk
  rw [tree.eraseAbort_terminalVectorQueries]
  exact hq _ hk

end OptimalQLS.LowerBounds
